global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: "verixa-dev"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "verixa-runtime"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8000"]
        labels:
          service: "runtime-gateway"

  - job_name: "verixa-control-plane-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8001"]
        labels:
          service: "control-plane-api"

  - job_name: "opa"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["opa:8181"]
        labels:
          service: "policy-engine"
